all:
  hosts:
    node1:
      ip: MY_IP
      ansible_host: "{{ ip }}"
      access_ip: "{{ ip }}"
  
  children:
    kube-master:
      hosts:
        node1:

    kube-node:
      hosts:
        node1:

    etcd:
      hosts:
        node1:

    k8s-cluster:
      children:
        kube-master:
        kube-node:
    calico-rr:
      hosts: {}
